<a href="https://colab.research.google.com/github/alexacheui/ateema_capstone/blob/main/access_script.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import requests
import pandas as pd

# Replace with the actual public URL provided by ngrok
public_url = "https://f743-34-168-187-133.ngrok-free.app"

response = requests.get(f"{public_url}/get_latest_data")

if response.status_code == 200:
    data = response.json()
    if isinstance(data, list) and len(data) > 0:
        df = pd.DataFrame(data)
        print("Latest DataFrame retrieved from the server:")
    else:
        print("No data available.")
else:
    print(f"Failed to retrieve data. Status code: {response.status_code}")
    print(response.text)

df.head()

Latest DataFrame retrieved from the server:

,_id,first_name,last_name,phone_number,email,travel_city,start_date,end_date,group_type,group_size,...,pref_dining,pref_beverage,pref_entertainment,pref_cultural,pref_outdoor,pref_education,pref_shop,comment,video_length,timestamp
0,66775ee4d213698aaf05cb0f,Lorem ipsum dolor,Lorem ipsum dolor,+34123456789,an_account@example.com,Chicago,2017-02-06,2017-02-06,Solo Trip,42,...,"Gourmet, Chicago","Wine, Cocktails","Live, Clubs","Art, Immersive","Outdoor, Boat","Kid-Friendly, Art","Shopping, Local",Lorem ipsum dolor,30 seconds,1719099108600